### ISSUE TITLE
cors problem

### ISSUE THREAD

**Issue by icaroramiires** [jodconverter/docker-image-jodconverter-examples#14]
Hello, 

I have a client running on localhost:8081 and docker jodconverter running on localhost:8080. when i send a post request i get color error:

`Cross-origin request blocked: The same origin policy (Same Origin Policy) prevents the remote resource from being read at http: // localhost: 8080 / lool / convert-to. (Reason: the CORS header 'Access-Control-Allow-Origin' is not present). `

**Comment by EugenMayer** [comment]
We do not set any CORS headers and we wont do that here. Use whatever nginx/traefik proxy in front of this service to align that to your likings
