### ISSUE TITLE
Drop root privileges

### ISSUE THREAD

**Issue by alangecker** [jodconverter/docker-image-jodconverter-examples#15]
Currently the container scripts including libreoffice runs as root. surely it is encapsulated in the container, but as root the attack surface is still much bigger.

Considering the complex nature of parsing office documents leading to security vulnerabilities and that the jodconverter presumably is normally fed with untrusted user data I think this should be changed :)

**Comment by EugenMayer** [comment]
I'am happy to accept any PR for that. Be sure to use standards like `gosu` if you implement that.
