### ISSUE TITLE
The docker image doesn't start

### ISSUE THREAD

**Issue by evserykh** [jodconverter/docker-image-jodconverter-examples#23]
I want to try the converter and got the following:

```
evgeniy@pc ~ λ docker run --memory 512m --rm -p 8080:8080 ghcr.io/eugenmayer/jodconverter:gui
evgeniy@pc ~ λ docker ps -a
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
evgeniy@pc ~ λ 
```

Do I miss something?

**Comment by carcuevas** [comment]
Also I cannot made it work with the docker run  but cloning the repo and building the app it will:

 
1.- After cloning the repo, modify the build part of the `makefile` with the following: 
```
build:
        docker build --target jodconverter-base . -t eugenmayer/jodconverter:base
        docker build --target gui . -t eugenmayer/jodconverter:gui
        docker build --target rest . -t eugenmayer/jodconverter:rest
```
2.- You can build with `make build`  as instructions (it will take some time while compiling)
3.- Execute `make start-gui` (also in instructions) and it's done :) 


At least for me.... for me what's not working is the REST version..  https://github.com/EugenMayer/docker-image-jodconverter/issues/24
