### ISSUE TITLE
jodconverter fails after 5K conversions

### ISSUE THREAD

**Issue by sboden** [jodconverter/docker-image-jodconverter-examples#25]
We've been putting the image eugenmayer/jodconverter:rest through tests. I tried to convert 30K documents in 1 go. The jodconverter fails after 5K conversions with a "disk space full" message, the container runs on an AWS environment using 20Gb "ephemeral storage".

Maybe some more aggressive pruning of logs/data could be implemented.

Regards,
Sven

**Comment by EugenMayer** [comment]
Feel free to add any PR for this purpose. Please open an issue that is a FR describing your needs if you are going to put the time into it. Happy to review the PR
