### ISSUE TITLE
At times the converter stops reponding...seems to be connected to reaching the maximum tasks per process...

### ISSUE THREAD

**Issue by djlawler** [jodconverter/docker-image-jodconverter-examples#7]
Here is the log:
[blow_up.txt](https://github.com/EugenMayer/docker-image-jodconverter/files/3326695/blow_up.txt)

**Comment by EugenMayer** [comment]
sorry, this is out of scope for this project - you can try at https://github.com/sbraconnier/jodconverter but this is rather amd example project / simple setup to run jodconverter in a docker container.

How you run this 24/7 in production is a very different topic, be it devops or infra wise. If you want to report a software bug, please use the repo mentioned

**Comment by djlawler** [comment]
> 
> 
> sorry, this is out of scope for this project - you can try at https://github.com/sbraconnier/jodconverter but this is rather amd example project / simple setup to run jodconverter in a docker container.
> 
> How you run this 24/7 in production is a very different topic, be it devops or infra wise. If you want to report a software bug, please use the repo mentioned

Thanks for the direction!  I think I found similar issues in that project and will investigate further...
